# Declare your Buildkite pipelines below
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-cel-examples
  description: Buildkite Pipeline for cel-examples
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/cel-examples

spec:
  type: buildkite-pipeline
  owner: group:security-service-integrations
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: cel-examples
      description: 
    spec:
      repository: elastic/cel-examples
      pipeline_file: ".buildkite/pipeline.yml"
      teams:
        security-service-integrations:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
